# src/main/resources/config/application.properties
#Parámetros de aplicación
app.nombre=Sistema de colectivos
app.version=1.0.0
# Configuración de persistencia (usado por la Factory)
persistencia.tipo=POSTGRESQL
# Internacionalización (es_ES, en_US, pt_BR, fr_FR, zh_CN)
idioma.actual=es_ES
