# Este archivo le dice a la Fábrica qué clase concreta debe crear
# para cada "nombre clave" que le pidamos.

#PARADA=colectivo.dao.secuencial.ParadaDAOArchivo
#LINEA=colectivo.dao.secuencial.LineaDAOArchivo
#TRAMO=colectivo.dao.secuencial.TramoDAOArchivo

PARADA=colectivo.dao.postgresql.ParadaDAOBD
LINEA=colectivo.dao.postgresql.LineaDAOBD
TRAMO=colectivo.dao.postgresql.TramoDAOBD
INTERFAZ=colectivo.interfaz.impl.consola.InterfazConsolaImpl

#INTERFAZ=colectivo.interfaz.impl.javafx.InterfazJavaFXImpl


